export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  authCallback: "/auth/callback",
  search: "/search",
  library: "/library",
  lives: "/lives",
  liveRoom: (roomId: string) => `/lives/${encodeURIComponent(roomId)}`,
  artistLive: "/artist/live",
  album: (albumId: string) => `/albums/${encodeURIComponent(albumId)}`,
  artistProfile: (artistId: string) => `/artists/${encodeURIComponent(artistId)}`,
  artistDashboard: "/artist",
  artistTracks: "/artist/tracks",
  artistAlbums: "/artist/albums",
  artistUpload: "/artist/upload",
  artistUploadForAlbum: (albumId: string) => `/artist/upload?albumId=${encodeURIComponent(albumId)}`,
  artistAlbumNew: "/artist/albums/new",
  artistTrackEdit: (trackId: string) => `/artist/tracks/${encodeURIComponent(trackId)}/edit`,
  artistAnalytics: "/artist/analytics",
  adminOverview: "/admin",
  adminUsers: "/admin/users",
  adminContent: "/admin/content",
  adminReports: "/admin/reports",
  adminModeration: "/admin/moderation",
  settings: "/settings",
} as const;

export const routePatterns = {
  album: "/albums/:albumId",
  artistProfile: "/artists/:artistId",
  liveRoom: "/lives/:roomId",
  artistTrackEdit: "/artist/tracks/:trackId/edit",
} as const;
